In [36]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix





# Membaca Data

In [17]:
csv_path="../Data/credircardinfo.csv"
df=pd.read_csv(csv_path)

In [18]:
df.head()

ID   Age  Gender  Salary  Job Married  Num_children  type_credit
0    1    25      M      350   Y       N             0            0
1    2    45      M     1300   Y       Y             2            2
2    3    35      F     1000   Y       Y             2            1
3    4    27      M      550   Y       N             0            1
4    5    28      F      500   Y       Y             0            0

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   ID            95 non-null     int64 
 1   Age           95 non-null     int64 
 2   Gender        95 non-null     object
 3   Salary        95 non-null     int64 
 4   Job           95 non-null     object
 5   Married       95 non-null     object
 6   Num_children  95 non-null     int64 
 7   type_credit   95 non-null     int64 
dtypes: int64(5), object(3)
memory usage: 6.1+ KB


In [20]:
df.describe()

ID         Age       Salary   Num_children  type_credit
count  95.000000   95.000000    95.000000     95.000000    95.000000
mean   48.000000   41.821053  1170.736842      1.726316     0.926316
std    27.568098   21.492195  1008.575193      1.627177     0.775175
min     1.000000   18.000000     0.000000      0.000000     0.000000
25%    24.500000   28.500000   550.000000      0.000000     0.000000
50%    48.000000   35.000000   900.000000      2.000000     1.000000
75%    71.500000   45.000000  1625.000000      3.000000     2.000000
max    95.000000  120.000000  5000.000000      6.000000     2.000000

# PreProssesing

In [38]:
df.isnull().sum()

ID              0
Age             0
Gender          0
Salary          0
Job             0
Married         0
Num_children    0
type_credit     0
dtype: int64

# Encoding Fitur Kategorikal

In [25]:

# Encode kolom Gender
le_gender = LabelEncoder()
df['Gender'] = le_gender.fit_transform(df['Gender'])

# Encode kolom Married
le_married = LabelEncoder()
df['Married'] = le_married.fit_transform(df['Married'])
# Encode kolom Job
le_married = LabelEncoder()
df['Job'] = le_married.fit_transform(df['Job'])


# Memisahkan Fitur dan Label

In [26]:
X = df.drop(columns=['type_credit'])  # Fitur
y = df['type_credit']  # Label


# Membagi Data Menjadi Training dan Testing

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normalisasi
Normalisasi atau penskalaan fitur untuk meningkatkan performa model.

In [32]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Membuat Model,Memprediksi,dan Menampilkan hasil Evaluasi berbagai Kernel


In [37]:
# Menggunakan berbagai kernel
kernels = ['linear', 'poly', 'rbf', 'sigmoid']

for kernel in kernels:
    print(f'\nKernel: {kernel}')
    
    # Membuat model SVM dengan kernel yang ditentukan
    svm_model = SVC(kernel=kernel)
    svm_model.fit(X_train, y_train)
    
    # Memprediksi data pengujian
    y_pred = svm_model.predict(X_test)
    
    # Evaluasi model
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    # Menampilkan hasil evaluasi
    print(f'Akurasi: {accuracy}')
    print('Laporan Klasifikasi:')
    print(report)
    print('Confusion Matrix:')
    print(conf_matrix)


Kernel: linear
Akurasi: 0.8421052631578947
Laporan Klasifikasi:
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         6
           1       0.70      1.00      0.82         7
           2       1.00      0.83      0.91         6

    accuracy                           0.84        19
   macro avg       0.90      0.83      0.84        19
weighted avg       0.89      0.84      0.84        19

Confusion Matrix:
[[4 2 0]
 [0 7 0]
 [0 1 5]]

Kernel: poly
Akurasi: 0.631578947368421
Laporan Klasifikasi:
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         6
           1       0.50      1.00      0.67         7
           2       1.00      0.33      0.50         6

    accuracy                           0.63        19
   macro avg       0.83      0.61      0.61        19
weighted avg       0.82      0.63      0.61        19

Confusion Matrix:
[[3 3 0]
 [0 7 0]
 [0 4 2]]

Kernel: rbf
Akuras